workflows:
  ios-release:
    name: Build iOS Release for App Store
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials  # Add your App Store Connect API key in Codemagic UI
      vars:
        APP_ID: "com.qwantumtech.learnandgrow"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.qwantumtech.learnandgrow"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean project
        script: flutter clean
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --build-name=2.0.1 \
            --build-number=$(($(app-store-connect get-latest-build-number "$APP_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email address
        notify:
          success: true
          failure: false
      # IPA BUILD ONLY - NO UPLOAD
      # The IPA will be built and available for download, but NOT uploaded to App Store
      # app_store_connect publishing is intentionally NOT configured here
