workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd learn_earn_mobile
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd learn_earn_mobile/ios && pod install && cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          cd learn_earn_mobile
          flutter build ipa --release
    artifacts:
      - learn_earn_mobile/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email address
        notify:
          success: true
          failure: false
