workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials # Add your App Store Connect API key here
      vars:
        APP_ID: "com.qwantumtech.learnandgrow"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.qwantumtech.learnandgrow"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install && cd ..
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=2.0.1 \
            --build-number=$(($(app-store-connect get-latest-build-number "$APP_ID") + 1))
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email address
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        
        # Optional: Submit for review after successful build
        submit_to_testflight: false
        submit_to_app_store: false
        
        # Optional: Beta groups for TestFlight
        # beta_groups:
        #   - group name 1
        #   - group name 2

